# Generated by Django 5.2.12 on 2026-03-09 15:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocuProcess',
            fields=[
                ('project_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_uuid', models.UUIDField(blank=True, db_index=True, help_text='The unique ID of the user from the authentication service', null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('reference_urls', models.JSONField(default=list, help_text='List of Vercel Blob URLs for reference docs')),
                ('question_urls', models.JSONField(blank=True, default=list, help_text='List of Vercel Blob URLs for question docs')),
                ('text_questions', models.JSONField(blank=True, default=list, help_text='List of text questions')),
                ('results_url', models.URLField(blank=True, help_text='Vercel Blob URL where the LLM final Q&A results are stored', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Execution metadata, token usage, time taken')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Process',
                'verbose_name_plural': 'Document Processes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_uuid', '-created_at'], name='docu_model__user_uu_9af83e_idx'), models.Index(fields=['user_uuid', 'status'], name='docu_model__user_uu_f5226e_idx'), models.Index(fields=['status', 'created_at'], name='docu_model__status_3f33cc_idx')],
            },
        ),
    ]
