# Generated by Django 5.2.11 on 2026-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocuProcess',
            fields=[
                ('project_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_uuid', models.CharField(blank=True, db_index=True, help_text='The unique ID of the user from the authentication service', max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('reference_urls', models.JSONField(default=list, help_text='List of Vercel Blob URLs for reference docs')),
                ('question_urls', models.JSONField(blank=True, default=list, help_text='List of Vercel Blob URLs for question docs')),
                ('text_questions', models.JSONField(blank=True, default=list, help_text='List of text questions')),
                ('results_url', models.URLField(blank=True, help_text='Vercel Blob URL where the LLM final Q&A results are stored', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Execution metadata, token usage, time taken')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Process',
                'verbose_name_plural': 'Document Processes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_uuid', '-created_at'], name='docu_model__user_uu_9af83e_idx'), models.Index(fields=['user_uuid', 'status'], name='docu_model__user_uu_f5226e_idx'), models.Index(fields=['status', 'created_at'], name='docu_model__status_3f33cc_idx')],
            },
        ),
    ]
