# Generated by Django 5.2.12 on 2026-03-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docuprocess',
            name='user_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='The unique ID of the user from the authentication service', null=True),
        ),
    ]
