# Generated by Django 5.2.12 on 2026-03-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docuprocess',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
