# Generated by Django 5.2.12 on 2026-03-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_model', '0002_alter_docuprocess_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docuprocess',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='docuprocess',
            name='text_questions',
        ),
        migrations.AddField(
            model_name='docuprocess',
            name='extracted_doc_urls',
            field=models.JSONField(blank=True, default=list, help_text='Vercel Blob URLs of the markdown-extracted reference documents'),
        ),
        migrations.AddField(
            model_name='docuprocess',
            name='ingestion_strategy',
            field=models.CharField(choices=[('VECTOR', 'Vector DB'), ('GRAPH', 'Knowledge Graph'), ('VECTORLESS', 'Vectorless / Raw Text'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='How this document was indexed (determines future retrieval options)', max_length=20),
        ),
        migrations.AddField(
            model_name='docuprocess',
            name='refined_question_urls',
            field=models.JSONField(blank=True, default=list, help_text='Vercel Blob URLs of the LLM-refined questions'),
        ),
    ]
