# Generated by Django 5.2.12 on 2026-03-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_model', '0003_remove_docuprocess_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docuprocess',
            name='project_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
