# Generated by Django 5.2.12 on 2026-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_model', '0005_alter_docuprocess_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='docuprocess',
            name='collection_name',
            field=models.CharField(blank=True, help_text='Name of the vector DB collection or graph DB namespace where this document is stored', max_length=255, null=True),
        ),
    ]
