# Generated by Django 5.2.12 on 2026-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_model', '0006_docuprocess_collection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='docuprocess',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docuprocess',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
