# Generated by Django 5.2.12 on 2026-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_model', '0007_docuprocess_description_docuprocess_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docuprocess',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
