# Generated by Django 5.2.12 on 2026-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_model', '0008_alter_docuprocess_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='docuprocess',
            name='grooming_data',
            field=models.JSONField(blank=True, default=dict, help_text='Optional field to store grooming data from graph of DocuAgent'),
        ),
    ]
