# Generated by Django 5.2.12 on 2026-04-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docu_model', '0009_docuprocess_grooming_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docuprocess',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DELETING', 'Deleting'), ('DELETED', 'Deleted')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
